/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminQueue: typeof import('./components/AdminQueue.vue')['default']
    AdminView: typeof import('./components/AdminView.vue')['default']
    Chat: typeof import('./components/Chat.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Queue: typeof import('./components/UserQueue.vue')['default']
    QueueForm: typeof import('./components/QueueForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserQueue: typeof import('./components/UserQueue.vue')['default']
    UserView: typeof import('./components/UserView.vue')['default']
  }
}
